require_relative 'screen.rb'

screen = Screen.new

screen.rect(1, 1)
screen.rotate_row(0, 5)
screen.rect(1, 1)
screen.rotate_row(0, 5)
screen.rect(1, 1)
screen.rotate_row(0, 3)
screen.rect(1, 1)
screen.rotate_row(0, 2)
screen.rect(1, 1)
screen.rotate_row(0,3)
screen.rect(1, 1)
screen.rotate_row(0,2)
screen.rect(1, 1)
screen.rotate_row(0,5)
screen.rect(1, 1)
screen.rotate_row(0,5)
screen.rect(1, 1)
screen.rotate_row(0,3)
screen.rect(1, 1)
screen.rotate_row(0,2)
screen.rect(1, 1)
screen.rotate_row(0,3)
screen.rect(2, 1)
screen.rotate_row(0,2)
screen.rect(1, 2)
screen.rotate_row(1,5)
screen.rotate_row(0,3)
screen.rect(1, 2)
screen.rotate_column(30,1)
screen.rotate_column(25,1)
screen.rotate_column(10,1)
screen.rotate_row(1,5)
screen.rotate_row(0,2)
screen.rect(1, 2)
screen.rotate_row(0,5)
screen.rotate_column(0,1)
screen.rect(4, 1)
screen.rotate_row(2,18)
screen.rotate_row(0,5)
screen.rotate_column(0,1)
screen.rect(3, 1)
screen.rotate_row(2,12)
screen.rotate_row(0,5)
screen.rotate_column(0,1)
screen.rect(4, 1)
screen.rotate_column(20,1)
screen.rotate_row(2,5)
screen.rotate_row(0,5)
screen.rotate_column(0,1)
screen.rect(4, 1)
screen.rotate_row(2,15)
screen.rotate_row(0,15)
screen.rotate_column(10,1)
screen.rotate_column(5,1)
screen.rotate_column(0,1)
screen.rect(14, 1)
screen.rotate_column(37,1)
screen.rotate_column(23,1)
screen.rotate_column(7,2)
screen.rotate_row(3,20)
screen.rotate_row(0,5)
screen.rotate_column(0,1)
screen.rect(4, 1)
screen.rotate_row(3,5)
screen.rotate_row(2,2)
screen.rotate_row(1,4)
screen.rotate_row(0,4)
screen.rect(1, 4)
screen.rotate_column(35,3)
screen.rotate_column(18,3)
screen.rotate_column(13,3)
screen.rotate_row(3,5)
screen.rotate_row(2,3)
screen.rotate_row(1,1)
screen.rotate_row(0,1)
screen.rect(1, 5)
screen.rotate_row(4,20)
screen.rotate_row(3,10)
screen.rotate_row(2,13)
screen.rotate_row(0,10)
screen.rotate_column(5,1)
screen.rotate_column(3,3)
screen.rotate_column(2,1)
screen.rotate_column(1,1)
screen.rotate_column(0,1)
screen.rect(9, 1)
screen.rotate_row(4,10)
screen.rotate_row(3,10)
screen.rotate_row(1,10)
screen.rotate_row(0,10)
screen.rotate_column(7,2)
screen.rotate_column(5,1)
screen.rotate_column(2,1)
screen.rotate_column(1,1)
screen.rotate_column(0,1)
screen.rect(9, 1)
screen.rotate_row(4,20)
screen.rotate_row(3,12)
screen.rotate_row(1,15)
screen.rotate_row(0,10)
screen.rotate_column(8,2)
screen.rotate_column(7,1)
screen.rotate_column(6,2)
screen.rotate_column(5,1)
screen.rotate_column(3,1)
screen.rotate_column(2,1)
screen.rotate_column(1,1)
screen.rotate_column(0,1)
screen.rect(9, 1)
screen.rotate_column(46,2)
screen.rotate_column(43,2)
screen.rotate_column(24,2)
screen.rotate_column(14,3)
screen.rotate_row(5,15)
screen.rotate_row(4,10)
screen.rotate_row(3,3)
screen.rotate_row(2,37)
screen.rotate_row(1,10)
screen.rotate_row(0,5)
screen.rotate_column(0,3)
screen.rect(3, 3)
screen.rotate_row(5,15)
screen.rotate_row(3,10)
screen.rotate_row(2,10)
screen.rotate_row(0,10)
screen.rotate_column(7,3)
screen.rotate_column(6,3)
screen.rotate_column(5,1)
screen.rotate_column(3,1)
screen.rotate_column(2,1)
screen.rotate_column(1,1)
screen.rotate_column(0,1)
screen.rect(9, 1)
screen.rotate_column(19,1)
screen.rotate_column(10,3)
screen.rotate_column(5,4)
screen.rotate_row(5,5)
screen.rotate_row(4,5)
screen.rotate_row(3,40)
screen.rotate_row(2,35)
screen.rotate_row(1,15)
screen.rotate_row(0,30)
screen.rotate_column(48,4)
screen.rotate_column(47,3)
screen.rotate_column(46,3)
screen.rotate_column(45,1)
screen.rotate_column(43,1)
screen.rotate_column(42,5)
screen.rotate_column(41,5)
screen.rotate_column(40,1)
screen.rotate_column(33,2)
screen.rotate_column(32,3)
screen.rotate_column(31,2)
screen.rotate_column(28,1)
screen.rotate_column(27,5)
screen.rotate_column(26,5)
screen.rotate_column(25,1)
screen.rotate_column(23,5)
screen.rotate_column(22,5)
screen.rotate_column(21,5)
screen.rotate_column(18,5)
screen.rotate_column(17,5)
screen.rotate_column(16,5)
screen.rotate_column(13,5)
screen.rotate_column(12,5)
screen.rotate_column(11,5)
screen.rotate_column(3,1)
screen.rotate_column(2,5)
screen.rotate_column(1,5)
screen.rotate_column(0,1)

screen.draw
puts screen.lightened_pixels_count
